In [8]:
import matplotlib.pyplot as plt

from qadence import *
import torch
from torch.autograd import grad

In [9]:
def generate_chebyshev_grid(n, a=0, b=0.9, requires_grad=True):
    k = torch.arange(n)
    chebyshev_nodes = torch.cos(torch.pi * (2*k + 1) / (2*n))  #standard Chebyshev nodes in [-1,1]
    scaled_nodes = ((chebyshev_nodes + 1) / 2) * (b - a) + a  #rescale to [a, b]
    
    return scaled_nodes.requires_grad_(requires_grad=requires_grad)

N_POINTS = 10
x = generate_chebyshev_grid(N_POINTS)
print(x)
cp = torch.reshape(x, (N_POINTS,1))

tensor([0.8945, 0.8510, 0.7682, 0.6543, 0.5204, 0.3796, 0.2457, 0.1318, 0.0490,
        0.0055], requires_grad=True)


In [ ]:
#N_POINTS = 10
#cp = torch.linspace(0.0, 0.9, N_POINTS, dtype=torch.float64)
#cp = torch.reshape(cp, (N_POINTS,1))
#print(cp)

tensor([[0.0000],
        [0.1000],
        [0.2000],
        [0.3000],
        [0.4000],
        [0.5000],
        [0.6000],
        [0.7000],
        [0.8000],
        [0.9000]])


### f(x)

In [10]:
N_QUBITS = 6

chebT = feature_map(n_qubits=N_QUBITS, param="x", op=RY, fm_type = BasisSet.CHEBYSHEV, reupload_scaling = ReuploadScaling.TOWER)
fm = chebT

obs = total_magnetization(N_QUBITS)
circuit = QuantumCircuit(N_QUBITS, fm)
model = QNN(circuit=circuit, observable=obs, inputs=["x"])

print(model(cp[9]))
print(model)

tensor([[-0.9830]], grad_fn=<CatBackward0>)
QNN(
  (_circuit): ConvertedCircuit(
    (native): QuantumCircuit(
      (operations): ModuleList(
        (0): Sequence(
          (operations): ModuleList(
            (0): RY(target: (0,), param: 1_0*acos(x))
            (1): RY(target: (1,), param: 2_0*acos(x))
            (2): RY(target: (2,), param: 3_0*acos(x))
            (3): RY(target: (3,), param: 4_0*acos(x))
            (4): RY(target: (4,), param: 5_0*acos(x))
            (5): RY(target: (5,), param: 6_0*acos(x))
          )
        )
      )
    )
  )
  (_params): ParameterDict(  (fix_1): Parameter containing: [torch.DoubleTensor of size 1])
)
